version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "5001:5001"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/src
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=users
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  db-data: